name: Deploy Plugin to Dev Site

on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install PHP Dependencies
        run: |
            composer clear-cache
            composer install --no-dev --optimize-autoloader
      - name: Install Node.js Dependencies
        run: npm install

      - name: Build Assets with Webpack
        run: npm run build
        
      - name: Deploy Dev to gishehcinema.ir
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DEV_SERVER: ${{ secrets.DEV_SERVER }}
          DEV_PATH: ${{ secrets.DEV_PATH }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          rsync -avz -vv --exclude 'private_key' --exclude-from='.github/exclude-list.txt' \
            -e "ssh -i private_key -o StrictHostKeyChecking=no" \
            ./ root@$DEV_SERVER:$DEV_PATH/

            
      - name: Fix File Ownership
        env:
          DEV_SERVER: ${{ secrets.DEV_SERVER }}
          DEV_PATH: ${{ secrets.DEV_PATH }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no root@$DEV_SERVER "chown -R www-data:www-data $DEV_PATH"
          rm -f private_key
